theme: minima
title: Angelo Carlino
author: postdoc @ Environmental Intelligence Lab, Politecnico di Milano <br>visiting postdoc @ Natural Capital Project, Stanford University

twitter_username: AngeloCarlino3
linkedin_username: angelo-carlino-570051170
orcid_username: 0000-0002-8403-9070
github_username: angelo-carlino
