theme: minima
title: Angelo Carlino
author: " "
description: postdoc @ Polimi, visiting postdoc @ Stanford

twitter_username: AngeloCarlino3
github_username: angelo-carlino
linkedin_username: angelo-carlino-570051170
orcid_username: 0000-0002-8403-9070
